server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: ms-admin-api
  flyway:
    locations: classpath:db/migration
  datasource:
    url: ${POSTGRESQL_HOST}
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASS}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: ${MAIL_ENABLE_SSL}
        transport:
          protocol: smtp
        from: ${MAIL_USER}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST}
    ssl:
      enabled: ${RABBITMQ_SSL}
api:
  security:
    secret: ${API_SECRET}

app:
  consumidor:
    urls: ${API_CORS_ALLOWED_ORIGINS}

asaas:
  token: ${ASAAS_TOKEN}
  url: ${ASAAS_URL}

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html

rabbitmq:
  exchanges:
    criar-oficinas: criar-oficinas.ex