spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/msadmindb
    username: postgres
    password: 102030
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 465
    username: 8d8137f576c7cb
    password: 4c9795c48db3d6
    smtp:
      auth: true
      starttls:
        enable: true
  rabbitmq:
    host: chimpanzee.rmq.cloudamqp.com
    port: 5671
    username: kouixnrk
    password: 7AB7frG82_OlFizS5TpuYyjHEt3hf-L1
    virtual-host: kouixnrk
    ssl:
      enabled: true
api:
  security:
    secret: 3cf6db6589fb49b871228515ca36f2edcc718ef4
app:
  consumidor:
    urls: http://localhost:9000
asaas:
  token: $aact_prod_000MzkwODA2MWY2OGM3MWRlMDU2NWM3MzJlNzZmNGZhZGY6OjIwZmVlZjVlLWI2YmMtNDdmNS04NDRjLTdjZGQyYjM1YTNlNDo6JGFhY2hfMjNmZWIwYTctOTk3ZS00Y2M2LThkZDAtOGE3N2RiMTBjZDhm
  url: https://api.asaas.com/v3