spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/msadmindb
    username: postgres
    password: 102030
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 465
    username: 8d8137f576c7cb
    password: 4c9795c48db3d6
    smtp:
      auth: true
      starttls:
        enable: true
  rabbitmq:
    host: localhost
    port: 5672
    username: ${rabbitmq.username}
    password: ${rabbitmq.password}
api:
  security:
    secret: ${security.secret}
app:
  consumidor:
    urls: http://localhost:9000

