spring:
  datasource:
    url: jdbc:postgresql://db:5432/ms_admin_db_product
    username: postgres
    password: 102030
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 465
    username: 8d8137f576c7cb
    password: 4c9795c48db3d6
    smtp:
      auth: true
      starttls:
        enable: true
  rabbitmq:
    host: rabbit-mq
    port: 5672
    username: guest
    password: guest

api:
  security:
    secret: 67e2abfb1dbca66eeabbddff4433b8af7b8c7961
app:
  consumidor:
    urls: http://localhost:9000
asaas:
  token: $aact_MzkwODA2MWY2OGM3MWRlMDU2NWM3MzJlNzZmNGZhZGY6OmEwNDAyZjQ2LWQ2YTAtNGM3ZS05YTYzLTMwNTlmMjk5N2RmMzo6JGFhY2hfZjIwNTllZDItYWQ1MC00YWM0LTk0ZGUtMjgzNWM2NDcwYTUz
  url: https://api-sandbox.asaas.com/v3