spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/msadmindb
    username: postgres
    password: 102030
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 465
    username: 8d8137f576c7cb
    password: 4c9795c48db3d6
    smtp:
      auth: true
      starttls:
        enable: true
  rabbitmq:
    host: localhost
    port: 5672
    username: ${rabbitmq.username}
    password: ${rabbitmq.password}

api:
  security:
    secret: ${security.secret}

app:
  consumidor:
    urls: http://localhost:9001

asaas:
  token: $aact_MzkwODA2MWY2OGM3MWRlMDU2NWM3MzJlNzZmNGZhZGY6OmEwNDAyZjQ2LWQ2YTAtNGM3ZS05YTYzLTMwNTlmMjk5N2RmMzo6JGFhY2hfZjIwNTllZDItYWQ1MC00YWM0LTk0ZGUtMjgzNWM2NDcwYTUz
  url: https://api-sandbox.asaas.com/v3