spring:
  datasource:
    url: ${postgresql.url}
    username: ${postgresql.username}
    password: ${postgresql.password}
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  mail:
    host: ${mail.host}
    port: ${mail.port}
    username: ${mail.host.user}
    password: ${mail.host.pass}
    smtp:
      auth: true
      starttls:
        enable: true
  rabbitmq:
    host: localhost
    port: 5672
    username: ${rabbitmq.username}
    password: ${rabbitmq.password}

api:
  security:
    secret: ${security.secret}

app:
  consumidor:
    urls: ${app.urls.consumers}

asaas:
  token: ${asaas.token}
  url: ${asaas.api.url}