spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms_admin_db
    username: postgres
    password: 102030
    driver-class-name: org.postgresql.Driver
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      defer-datasource-initialization: true
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 465
    username: 8d8137f576c7cb
    password: 4c9795c48db3d6
    smtp:
      auth: true
      starttls:
        enable: true
api:
  security:
    secret: ${security.secret}
app:
  consumidor:
    urls: http://localhost:9000
