CREATE TABLE IF NOT EXISTS clientes (
    id VARCHAR(150) NOT NULL PRIMARY KEY DEFAULT REPLACE(uuid_generate_v4()::text, '-',''),
    tipo CHAR(2) NOT NULL DEFAULT 'PF',
    cpf_cnpj VARCHAR(20) NOT NULL UNIQUE,
    razao VARCHAR(150) NOT NULL,
    nm_fantasia VARCHAR(150) NOT NULL UNIQUE,
    proprietario VARCHAR(150),
    cpf_propr VARCHAR(11),
    vencimento INTEGER DEFAULT '0',
    integrado boolean NOT NULL DEFAULT 'false',
    ativo boolean NOT NULL DEFAULT 'false',
    modulo CHAR(3),
    plano CHAR(5),
    cep VARCHAR(10) NOT NULL,
    logradouro VARCHAR(150) NOT NULL,
    bairro VARCHAR(100) NOT NULL,
    cidade VARCHAR(100) NOT NULL,
    uf CHAR(2) NOT NULL DEFAULT 'PI',
    complemento TEXT,
    latitude VARCHAR(60),
    longitude VARCHAR(60),
    periodo_teste BOOLEAN DEFAULT 'false',
    total_dias_teste INT DEFAULT '0',
    dt_vencimento_teste DATE,
    dt_criado_em DATE NOT NULL DEFAULT 'now()',
    dt_atualizado_em DATE
);