name: Build and Publish Docker Image

on:
  push:
    branches:
      - develop  # ou 'master', se for o caso

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache dependências Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Compilar aplicação
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t ms-admin-api .

      # Se quiser publicar no Docker Hub:
      - name: Login no Docker Hub
        if: github.ref == 'refs/heads/main'
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag & Push Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag ms-admin-api ${{ secrets.DOCKER_USERNAME }}/ms-admin-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ms-admin-api:latest
